defaults:
  - task: overcooked/cramped_room # task configs
  - hydra: hydra_simple
  - ../../evaluation/configs/global_heldout_settings
  - algorithm@algorithm: ppo_ego/${task} # task-specific algorithm configs
  - _self_         # Ensures that values in this file override imported ones if needed

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
ROLLOUT_LENGTH: ${task.ROLLOUT_LENGTH}
TASK_NAME: ${task.TASK_NAME}

run_heldout_eval: true

partner_agent:
  name: persistent_paired # overcooked cramped room
  path: "results/overcooked-v1/cramped_room/oe_persistent_paired/method-explore:uniform/2025-04-30_00-47-07/saved_train_run"
  actor_type: actor_with_double_critic
  custom_loader: 
    name: open_ended # if null, use default loader
    type: ego # options: ego, partner
  ckpt_key: final_buffer
  idx_list: [[0, -1]]
  
  # name: ippo_mlp # lbf policy!
  # path: "eval_teammates/lbf/ippo/2025-04-21_23-41-17/saved_train_run"
  # actor_type: mlp
  # ckpt_key: final_params
  # idx_list: null # null to load all agents
  # provide any necessary args to initialize the agent here
  # ex) S5_ACTOR_CRITIC_HIDDEN_DIM: 64 
  # defaults for each actor type will be used if no args are provided

algorithm:
  ALG: ppo_ego
  EGO_ACTOR_TYPE: s5 # options: s5, mlp, rnn
  TRAIN_SEED: 12345
  NUM_EGO_TRAIN_SEEDS: 3
  NUM_EVAL_EPISODES: 20
  NUM_CHECKPOINTS: 5
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH}

label: ""
name: ${TASK_NAME}/${algorithm.ALG}_${algorithm.EGO_ACTOR_TYPE}/${label}

# WandB Params
logger: 
  project: open-ended-aht
  entity: aht-project
  tags: 
    - ${algorithm.ALG}
    - ${TASK_NAME}
    - ${label}
  mode: online # options: online, offline, disabled
  verbose: false
  log_train_out: true # whether to log the out dictionary
  log_eval_out: true # whether to log the eval metrics

# Local logger
local_logger:
  save_figures: true # currently unused
  save_train_out: true
  save_eval_out: true