defaults:
  - hydra: hydra_simple
  - _self_         # Ensures that values in this file override imported ones if needed

ENV_NAME: lbf
ROLLOUT_LENGTH: 128 # rollout length must be greater than episode length
ENV_KWARGS: {}

algorithm:
  ALG: ppo_s5
  TOTAL_TIMESTEPS: 3e5
  TRAIN_SEED: 38410
  NUM_EGO_TRAIN_SEEDS: 1
  NUM_EVAL_EPISODES: 20
  NUM_CHECKPOINTS: 5
  NUM_ENVS: 16
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH}
  LR: 1.e-4 
  UPDATE_EPOCHS: 15
  NUM_MINIBATCHES: 4
  GAMMA: 0.99
  GAE_LAMBDA: 0.95
  CLIP_EPS: 0.05
  ENT_COEF: 0.01
  VF_COEF: 1.0
  MAX_GRAD_NORM: 1.0
  ANNEAL_LR: true
  S5_ACTOR_CRITIC_HIDDEN_DIM: 64
  S5_D_MODEL: 16
  S5_SSM_SIZE: 16
  S5_N_LAYERS: 2
  S5_BLOCKS: 1
  S5_ACTIVATION: full_glu
  S5_DO_NORM: true
  S5_PRENORM: true
  S5_DO_GTRXL_NORM: true

# WandB Params
logger: 
  project: open-ended-aht
  entity: aht-project
  mode: online # options: online, offline, disabled
  verbose: true
  log_train_out: false # whether to log the out dictionary

# Local logger
local_logger:
  save_figures: true # currently unused
  save_train_out: true

hydra:
  job:
    name: ppo_ego_s5
    chdir: true
  run:
    dir: results/${ENV_NAME}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
