defaults:
  - ippo_defaults@PARTNER_TRAIN_ARGS   # import default values to PARTNER_TRAIN_ARGS
  - fcp_s5_defaults@FCP_TRAIN_ARGS   # import default values to FCP_TRAIN_ARGS
  - _self_         # Ensures that values in this file override imported ones if needed

# ENV_NAME: overcooked
# ENV_KWARGS: {"layout": "cramped_room"}

ENV_NAME: lbf
EPISODE_LENGTH: 128
ENV_KWARGS: {}

PARTNER_TRAIN_ARGS: 
  TOTAL_TIMESTEPS: 1e6 # specify arg to override default value
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  NUM_STEPS: ${EPISODE_LENGTH}
  # set to null to train from scratch
  TRAIN_PATH: null
  TRAIN_SEED: 1285842
  # set to null to train from scratch
  EVAL_PATH: null
  EVAL_SEED: 112358

FCP_TRAIN_ARGS: 
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  NUM_STEPS: ${EPISODE_LENGTH}
  SEED: 38410

FCP_EVAL_ARGS: 
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  NUM_STEPS: ${EPISODE_LENGTH}
  SEED: 12345

# WandB Params
ENTITY: 
PROJECT: aht-project
WANDB_MODE : disabled

# Hydra params
hydra:
  job:
    name: fcp_s5
    chdir: true
  run:
    dir: results/${ENV_NAME}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
