TOTAL_TIMESTEPS: 3e5 
LR: .0001
NUM_ENVS: 16
ROLLOUT_LENGTH: 128 # rollout length
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 8
NUM_CHECKPOINTS: 5
NUM_SEEDS: 3
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.05
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 1.0
ANNEAL_LR: True
# s5 ego defaults
S5_ACTOR_CRITIC_HIDDEN_DIM: 64
S5_D_MODEL: 16
S5_SSM_SIZE: 16
S5_N_LAYERS: 2
S5_BLOCKS: 1
S5_ACTIVATION: full_glu
S5_DO_NORM: True
S5_PRENORM: True
S5_DO_GTRXL_NORM: True
