# @package algorithm
# ^ tells hydra to place these value directly under algorithm key
ALG: lbrdiv
TOTAL_TIMESTEPS: 4.5e7  # divided among each pair of BR and Conf agents
NUM_CHECKPOINTS: 5
PARTNER_POP_SIZE: 4
NUM_ENVS_SP: 32
NUM_ENVS_XP: 32
TOLERANCE_FACTOR: 0.1 # specific to L-BRDiv
LAGRANGE_LR: 0.1 # specific to L-BRDiv
LR: 1e-4
UPDATE_EPOCHS: 15
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.05
ENT_COEF: 0.01
VF_COEF: 1.0
MAX_GRAD_NORM: 1.0
ANNEAL_LR: false
