defaults:
  - open_ended_lagrange/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 3e6
TIMESTEPS_PER_ITER_EGO: 1e6
NUM_OPEN_ENDED_ITERS: 30
LOWER_REGRET_THRESHOLD_START: 0.0
LOWER_REGRET_THRESHOLD_END: 0.0
UPPER_REGRET_THRESHOLD_START: 60.0
UPPER_REGRET_THRESHOLD_END: 60.0
LAGRANGE_MULTIPLIER_LR: 0.01
LR: .0001
NUM_MINIBATCHES: 8
CLIP_EPS: 0.3
ENT_COEF: 0.01
ANNEAL_LR: false
EGO_ARGS:
  LR: 5e-5
  ENT_COEF: .001
  CLIP_EPS: 0.1
  UPDATE_EPOCHS: 10
