# heldout set
EVAL_SEED: 34957
MAX_EPISODE_STEPS: 400 # evaluation will use true episode length
NUM_EVAL_EPISODES: 32

heldout_set:
  lbf: # doesn't matter what you name each agent
    brdiv: 
      path: "eval_teammates/lbf/brdiv/2025-04-16/11-32-07/saved_train_run"
      actor_type: actor_with_conditional_critic
      idx_list: [[0, -1], [1, -1], [2, -1]] # If null, all checkpoints will be loaded.
      ckpt_key: checkpoints_conf # key to load from checkpoint. default is "checkpoints"
      POP_SIZE: 5 # for brdiv, we need to specify population size that the method was trained with
    ppo_ego_s5: 
      path: "results/lbf/ppo_ego_s5/2025-04-13_11-43-33/saved_train_run"
      actor_type: s5
      idx_list: [[0, -1]]
    # random_agent: 
    #   actor_type: random_agent
  overcooked-v1:
    random_agent:
      actor_type: random_agent
    static_agent:
      actor_type: static_agent
    independent_agent:
      actor_type: independent_agent
    onion_agent:
      actor_type: onion_agent
    plate_agent:
      actor_type: plate_agent