defaults:
  - brdiv/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 6e6
PARTNER_POP_SIZE: 30
LR: .0001
UPDATE_EPOCHS: 15
CLIP_EPS: 0.3
ENT_COEF: 0.01